name: Second work flow
on: push
jobs:
  Hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: hi guthub
        run: echo "Hello, this is the first workflow"

  bye-job:
    runs-on: ubuntu-latest

    steps:
      - name: bye guthub
        run: echo "Hello, this is the first workflow"
